### ISSUE TITLE
Script not loaded on route change (Vue.js)

### ISSUE THREAD

**Issue by kimthanh932000** [mdbootstrap/Black-Friday-2025#10]
I'm trying to integrate Material + Bootstrap 5 to an existing project using Vue.js + Bootstrap 4.

`mdb.min.css`  is imported in `main.js` and it's working just fine. But I have to import `mdb.min.js` in `mounted` hook in `App.vue` for it to work.

The problem is that `mdb.min.js` is not loaded on route change (`vue-router`) so the styles for input fields are missing. Whenever route changed, I have to refresh page for the script to work again.

I'm not sure whether I import the script incorrectly or is it the problem with current mdb version? Is there a way to fix it?

I always get below error message on route change and you can see the styles for inputs are missing

I also tested with the CDN but it still produced the same errors on route change

![error](https://user-images.githubusercontent.com/30076762/89898835-96bde600-dc0b-11ea-8f01-11376918f91d.PNG)

**Comment by smolenski-mikolaj** [comment]
MDB5 Vue integration is only in the plans for the future. As soon as there will be an alpha version, we will inform.
