### ISSUE TITLE
Disable cookies in production

### ISSUE THREAD

**Issue by hkimani** [mdbootstrap/Black-Friday-2025#11]
Hi, First of all, I love the framework and appreciate your work. 

Is there a way to disable the cookies that are been set on the client-side from the domain: mdbootstrap.com, I don't see the need for them since I'm not using a CDN.

Here's a screen shot:
![mdb](https://user-images.githubusercontent.com/43814350/91489687-e235ec80-e8b9-11ea-9da7-8f17e79839fb.png)

**Comment by filipkappa** [comment]
Hello,

If you clear the cookies and visit the website you'll have an option to manage some of the cookies in accordance with the privacy policy: https://mdbootstrap.com/general/privacy-policy/


Some of the 1st party cookies serve the functionality of the website and cannot be turned off.

Best regards,
Filip from MDB

**Comment by hkimani** [comment]
Okay, understood. 
I noticed the cookies were being set when requesting a cross-site resource (image from mdbootstrap) and chrome throws the warning:

![mdbwarn](https://user-images.githubusercontent.com/43814350/91550775-bce4c500-e931-11ea-9376-2f200455a3f8.png)

Changing the image source solved the issue for me.

Thank you.
