### ISSUE TITLE
null error occurred in tooltip

### ISSUE THREAD

**Issue by famibee** [mdbootstrap/Black-Friday-2025#12]
If you repeatedly mouse over or off the "X" button at high speed, an error will occur.
「X」ボタン上でマウスオーバーしたり外したりを高速で繰り返すと、エラーになります。

MDB 5 : Release 1.1.0, 1.0.0
Google Chrome は最新版です　バージョン: 85.0.4183.102（Official Build） （64 ビット）
(The same was true for Firefox 80.0.1 (64 bit))
（Firefox 80.0.1 (64 ビット)でも同じでした）

---
`&lt;!doctype html&gt;&lt;html&gt;
&lt;head&gt;&lt;meta charset=&quot;utf-8&quot;/&gt;
&lt;link rel=&quot;stylesheet&quot; href=&quot;mdb.min.css&quot;&gt;
&lt;script defer src=&quot;mdb.min.js&quot;&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;

&lt;nav class=&quot;navbar fixed-top navbar-expand navbar-dark bg-dark&quot;&gt;
&lt;div class=&quot;container-fluid&quot;&gt;

	<div class="collapse navbar-collapse mr-auto">
		<button id="close" type="button" class="btn btn-outline-light py-0" aria-label="Close" data-toggle="tooltip" title="Close">
			<span style="font-size: 2em;" aria-hidden="true">&times;</span>
		</button>
	</div>

&lt;/div&gt;
&lt;/nav&gt;

&lt;/body&gt;&lt;/html&gt;`

---
mdb.min.js:44 Uncaught TypeError: Cannot read property 'destroy' of null
    at t (mdb.min.js:44)
    at r.value (mdb.min.js:44)
    at r.value (mdb.min.js:44)
    at HTMLSpanElement.<anonymous> (mdb.min.js:44)
    at HTMLSpanElement.t (mdb.min.js:44)
[tooltip.zip](https://github.com/mdbootstrap/mdb-ui-kit/files/5195904/tooltip.zip)

**Comment by smolenski-mikolaj** [comment]
I suggest to add the following style to the span element to enable tooltip for the whole button: 
`pointer-events: none`

**Comment by famibee** [comment]
Thanks!
