### ISSUE TITLE
Leading and Trailing icons in textfields.

### ISSUE THREAD

**Issue by bernalandres** [mdbootstrap/Black-Friday-2025#13]
Hello. I have the following drawbacks. I use the min version 1.1.0 of mdb-ui-kit (both css and js from CDN). mdb4 classes for input leading and trailing icons are not supported for mdb5?. Is there structure and classes for it in mdb5?. Is the character counter already implemented in the form-outline?. If the answer is no, do you plan to add it?. 
![input_leading_trailing](https://user-images.githubusercontent.com/51427948/93470442-ed2fdb80-f8bf-11ea-8168-c73fe0ad2bef.PNG)

**Comment by smolenski-mikolaj** [comment]
For this moment we don't support leading and trailing icons and have no plans for it. We do support input groups. Here's our documentation: https://mdbootstrap.com/docs/standard/forms/input-group/.
