### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by satoufuyuki** [mdbootstrap/Black-Friday-2025#14]
Hi! I'm trying to using `mdb-ui-kit` with react, but when I compile the react, `mdb.min.css` throwing this error:
![image](https://user-images.githubusercontent.com/45705890/94245899-2104a400-ff45-11ea-9ef4-4603f65d7b67.png)
Is `mdb-ui-kit` doesn't support react?

**Comment by smolenski-mikolaj** [comment]
We are going to prepare an individual React package, however in this case I suppose You need to add a CSS loader to your project. The file with errors is just a plain CSS stylesheet that should work in any web framework or library.
