### ISSUE TITLE
input element is not working if it is created on the fly

### ISSUE THREAD

**Issue by mannok** [mdbootstrap/Black-Friday-2025#16]
When I created some `<input />`, supposed that a border would be generated as well. i.e. sth like `.form-notch`. However, these elements was not generated if such `<input />` is created on the fly.

UPDATE:
Seems that `MutationObserver` is not working in this version. i.e. `input` notch is not applied If I created an element after page rendered.

UPDATE (replay method):
Please go to https://mdbootstrap.com/docs/standard/forms/input-fields/ and paste those code in dev console. You will find that an input element with no-border will be create at the bottom of the page.

```
var wrapper = document.createElement('div');
wrapper.classList.add('form-outline')

var input = document.createElement('input');
input.id = 'form111';
input.classList.add('form-control');

var label = document.createElement('label');
label.classList.add('form-label');
label.setAttribute('for', 'form111');
label.innerText = 'Example Label'

wrapper.appendChild(input);
wrapper.appendChild(label);

document.body.appendChild(wrapper);
```

**Comment by smolenski-mikolaj** [comment]
For dynamic loaded input it's necessary to make a manual initialization. 

Here's the instruction: https://mdbootstrap.com/docs/standard/forms/input-fields/#section-dynamic-input-initialization

**Comment by ViRuSTriNiTy** [comment]
@smolenski-mikolaj Same goes for all the other components.

**Comment by ViRuSTriNiTy** [comment]
@smolenski-mikolaj The documentation states `new mdb...` but I get `Uncaught ReferenceError: mdb is not defined`. Before you posted your comment I had to figure it out by myself and this works for me in case of drop-downs:

`new $.fn.dropdown.Constructor(dropdown, {});`

This line needs jQuery but it works. I use the npm package `mdb-ui-kit`. Now I wonder how I get `mdb` defined. Any ideas?

**Comment by smolenski-mikolaj** [comment]
Here you can find the instruction of NPM installation: https://mdbootstrap.com/docs/standard/getting-started/installation/#section-npm

The important thing is the import statement:
`import * as mdb from 'mdb-ui-kit';`

**Comment by ViRuSTriNiTy** [comment]
Ok, this works only for node applications but I am just installing the node package and transform the sources via gulp into a bundle that I then use im my web application. I guess it is an edge case not really supported, isn't it?
