### ISSUE TITLE
Ripple effect should be displayed on mouse down instead of mouse up

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [mdbootstrap/Black-Friday-2025#17]
Hi there,

I'm currently migrating from https://github.com/mdbootstrap/bootstrap-material-design to mdb-ui-kit.

Unfortunately the ripple effect is displayed on mouse up instead of mouse down as it was implemented in `bootstrap-material-design`.

Even the [Google demo](https://material-components.github.io/material-components-web-catalog/#/component/ripple) displays it that way.

Would be nice if you can follow the Google specifications. What do you say?

So lonG
Daniel

**Comment by smolenski-mikolaj** [comment]
Thanks for paying attention to this issue. We'll fix it soon.

**Comment by smolenski-mikolaj** [comment]
Fixed with today's release (2.2.1).

**Comment by ViRuSTriNiTy** [comment]
Great, thank you.
