### ISSUE TITLE
Configure MD Bootstrap5 correctly

### ISSUE THREAD

**Issue by Haso5894** [mdbootstrap/Black-Friday-2025#18]
Hi,

I have an NRWL Angular project, I bought the pro essential pack of MD Bootstrap 5 and was following this tutorial: [https://www.youtube.com/watch?v=Ro1x0zYUwwA](url) But at the very first step I have already problems. The sidebar copied in the tutorial works directly in the tutorial, with its dropdowns and responsivness, but when I do it I get a sidebar, the dropdowns are not working (Do not show the option). And there is a button which works in the component webpage but not with me.

I do not want to import the styles or the scripts in my html but in my angular.json which I did and looks like this:

```
 "styles": [
          "apps/moniesta-admin/src/styles.scss",
          "node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss",
          "node_modules/@fortawesome/fontawesome-free/scss/solid.scss",
          "node_modules/@fortawesome/fontawesome-free/scss/regular.scss",
          "node_modules/@fortawesome/fontawesome-free/scss/brands.scss",
          "node_modules/ng-uikit-pro-standard/assets/scss/bootstrap/bootstrap.scss",
          "node_modules/ng-uikit-pro-standard/assets/scss/mdb.scss",
          "node_modules/animate.css/animate.css",
          "node_modules/bootstrap/scss/bootstrap.scss",
          "node_modules/mdb-ui-kit/css/mdb.min.css",
          "node_modules/mdb-ui-kit/src/scss/mdb.core.scss",
          "node_modules/mdb-ui-kit/src/scss/mdb.free.scss",
          "node_modules/mdb-ui-kit/src/scss/mdb.pro.scss"


        ],
        "scripts": [
          "node_modules/chart.js/dist/Chart.js",
          "node_modules/easy-pie-chart/dist/easypiechart.js",
          "node_modules/screenfull/dist/screenfull.js",
          "node_modules/hammerjs/hammer.min.js",
          "node_modules/bootstrap/dist/js/bootstrap.js",
          "node_modules/mdb-ui-kit/js/mdb.min.js",
          "node_modules/mdb-ui-kit/src/js/mdb.pro.js",
          "node_modules/mdb-ui-kit/src/js/mdb.free.js"


          ]
      },
```

Is my configuration wrong?

**Comment by smolenski-mikolaj** [comment]
MDB UI KIT and Admin Dashboard tutorial is made for Vanilla JS. Angular, Vue and React versions are going to be released in a few months.

**Comment by Haso5894** [comment]
So I already bought it, does that mean if it comes out for angular I have to buy again?

**Comment by smolenski-mikolaj** [comment]
Yes, it will be a brand new project built from scratch with the latest version of Angular, Bootstrap, and Material Design.

**Comment by Haso5894** [comment]
can I get a refund then? I did not know this and as it is now, it is useless for me sadly, I need it for Angular.

**Comment by bwsky-a** [comment]
Hello, please describe your problem in an email and send it to us at contact@mdbootstrap.com

**Comment by Haso5894** [comment]
I did but still no answer sadly its already 2 days

**Comment by bwsky-a** [comment]
I have already replied to your email

**Comment by smolenski-mikolaj** [comment]
I'm closing the thread because the discussion has been moved to an e-mail.
