### ISSUE TITLE
Some weird error

### ISSUE THREAD

**Issue by thrace19** [mdbootstrap/Black-Friday-2025#19]
![image](https://user-images.githubusercontent.com/40756526/98685573-88f43a00-238d-11eb-9518-ec9f373a849e.png)

**Comment by Lerie82** [comment]
Do you have a DIV named **#247Modal**

**Comment by smolenski-mikolaj** [comment]
First of all, I recommend to use the latest mdb-ui-kit package and check the issue again. Latest version number is **2.1.0**.

**Comment by smolenski-mikolaj** [comment]
Cosing thread due to no response.
