### ISSUE TITLE
What about to drop SASS of the base code?

### ISSUE THREAD

**Issue by OdairTrujillo** [mdbootstrap/Black-Friday-2025#4]
Some of you have proposed to left out SASS of the scope of this new version in favor of pure CSS?  

Is there any discussion of this somewhere?  

We all know that now we have CSS variables and the upcoming :is() function in Selector Level 4 that is being rapidly adopted by the web browsers market. So, is it worth to keep using SASS in this new version of MDMBootstrap?

**Comment by Martussky** [comment]
Hi,

SASS gives more possibilities than pure CSS and for now, we don't think about quitting SASS. Please, look at our SASS tutorial: https://www.youtube.com/watch?v=nasTBGf6frs.

Best, Marta

**Comment by OdairTrujillo** [comment]
Thanks for take your time to answer.
