### ISSUE TITLE
Input field is missing border

### ISSUE THREAD

**Issue by m-jovanovic** [mdbootstrap/Black-Friday-2025#6]
I have a simple login form and I'm trying to add two inputs for email and password but I can't seem to make the borders appear. I'm using the latest (alpha2) release.

![image](https://user-images.githubusercontent.com/34191235/87208010-b791d380-c30d-11ea-9dda-d5c2158ec187.png)

Here's my example HTML:

![image](https://user-images.githubusercontent.com/34191235/87208193-2707c300-c30e-11ea-92e1-3034523dce3a.png)

Note that I am wrapping the input fields inside of a div with card class applied. Would that somehow be the cause of the issue?
I would be very appreciative if you could give me any advice.

**Comment by smolenski-mikolaj** [comment]
It looks like you added mdb styles, but forgot to add mdb JS, which is necessary in this case. Please make sure you have imported MDB JS.

**Comment by m-jovanovic** [comment]
Confirming that the CSS and JS files are properly imported, and I still don't see any border around the inputs.

Also worth mentioning that I'm using **Edge**. But I'm also seeing in **Chrome**.

![image](https://user-images.githubusercontent.com/34191235/87562372-3bf1a700-c6be-11ea-9956-0a409eb9ebe4.png)

**Comment by m-jovanovic** [comment]
After downloading the latest (alpha 3) release, and testing it out I get the following error in console.

![image](https://user-images.githubusercontent.com/34191235/87563347-64c66c00-c6bf-11ea-8ac0-f23df9b0d5d4.png)

**Comment by smolenski-mikolaj** [comment]
The latest release (alpha4) updated input component. All input issues should not happen anymore.
