### ISSUE TITLE
"Python Book Bundle" is over

### ISSUE THREAD

**Issue by Pandorin** [mdbootstrap/Black-Friday-2025#66]
> 💸 (PAY WHAT YOOU WANT) [Python Book Bundle](https://www.humblebundle.com/books/python-programming-oreilly-books)
But:
`THE BUNDLE YOU'RE LOOKING FOR IS OVER
THIS BUNDLE WAS LIVE FROM NOV 15, 2021 TO DEC 6, 2021 WITH 17,217 BUNDLES SOLD, LEADING TO €24,964 RAISED FOR CHARITY.`

**Comment by MaciejZimoch** [comment]
Thx! Fixed.
