### ISSUE TITLE
Input field not design perfectly. 

### ISSUE THREAD

**Issue by devakb** [mdbootstrap/Black-Friday-2025#7]
![Issue MDB](https://user-images.githubusercontent.com/60037798/87301041-817e6a80-c52c-11ea-9d38-6910465db12e.PNG)

**Comment by smolenski-mikolaj** [comment]
Could you share your code? Do have the same problem in our documentation? https://mdbootstrap.com/docs/standard/forms/input-fields/

**Comment by devakb** [comment]
![issu](https://user-images.githubusercontent.com/60037798/87457976-e0c0a580-c626-11ea-9a8f-f8693ae7fc96.jpg)

 **Q) Do have the same problem in our documentation?**
Ans: Yes Sir

Thank you for your response

**Comment by smolenski-mikolaj** [comment]
Could You provide any details about Your system and browser? Still, I can't recreate the issue. 
Are You sure that You have imported MDB JS, not only CSS files? JS is needed to calculate label width in this case.

**Comment by devakb** [comment]
Dear Sir

My System is Windows 10;
My Browser is Chrome Latest Version.

I am included CSS and JS file.

**Comment by smolenski-mikolaj** [comment]
The latest release (alpha4) updated input component. All input issues should not happen anymore.
