### ISSUE TITLE
README.md weird look on github

### ISSUE THREAD

**Issue by andriussok** [mdbootstrap/Black-Friday-2025#8]
Is it only for me or README.md file don't load fully on github?
MacOs Mojave, left - Chrome, right - Safari.
![screencapture-github-mdbootstrap-mdb-ui-kit-blob-master-README-md-2020-07-23-08_31_38](https://user-images.githubusercontent.com/40456865/88262925-043bbe00-ccc1-11ea-88cc-f10609a172a9.jpg)

**Comment by smolenski-mikolaj** [comment]
Fixed by updating README file.
